<a href="https://colab.research.google.com/github/Jorge-89/Regresiones_TP_UNSAM/blob/main/SVM_Regresion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importo librerias necesarias
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error as mse
from sklearn.pipeline import Pipeline
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
#se importa el set de datos
url = 'https://raw.githubusercontent.com/Jorge-89/Regresion-Lineal-/main/base_datos_estaciones_met_V3_train.csv'
df = pd.read_csv(url, sep=",")
df.columns

Index(['Unnamed: 0', 'fecha_completa', 'Fecha', 'Hora',
       'Temp_Alicia AgriculturaCba', 'Humedad_Alicia AgriculturaCba',
       'PP_Alicia AgriculturaCba', 'Temp_Las Varas AgriculturaCba',
       'Humedad_Las Varas AgriculturaCba', 'PP_Las Varas AgriculturaCba',
       'Temp_San Miguel - Establecimiento Don Luis',
       'Humedad_San Miguel - Establecimiento Don Luis',
       'PP_San Miguel - Establecimiento Don Luis',
       'Temp_San Miguel - Listello', 'Humedad_San Miguel - Listello',
       'PP_San Miguel - Listello', 'Temp_ San Miguel - Las Varillas',
       'Humedad_ San Miguel - Las Varillas', 'PP_ San Miguel - Las Varillas'],
      dtype='object')

In [3]:
x= df[[ 'Temp_Las Varas AgriculturaCba', 'Humedad_Las Varas AgriculturaCba',
        'Temp_San Miguel - Establecimiento Don Luis', 'Humedad_San Miguel - Establecimiento Don Luis',
       'Temp_San Miguel - Listello', 'Humedad_San Miguel - Listello',
       'Temp_ San Miguel - Las Varillas', 'Humedad_ San Miguel - Las Varillas']]
y= df["Temp_Alicia AgriculturaCba"]

In [4]:
#Separo los datos de "train" en entrenamiento y prueba "test" para probar los algoritmos
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
modelo= Pipeline([('scaler', StandardScaler()),
                    
                  ('model',SVR())
])

grilla = GridSearchCV(modelo,
                      [{ 'model__C':[1,10,100,1000],'model__kernel':['linear']},{'model__gamma':[0.1,0.001], 'model__C':[1000,10000],'model__kernel':['rbf']}],
                      cv = 5, scoring="neg_mean_squared_error",verbose=3
                      )
grilla.fit(x_train,y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits
[CV] model__C=1, model__kernel=linear ................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ... model__C=1, model__kernel=linear, score=-0.613, total=   3.8s
[CV] model__C=1, model__kernel=linear ................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.8s remaining:    0.0s


[CV] ... model__C=1, model__kernel=linear, score=-0.631, total=   3.6s
[CV] model__C=1, model__kernel=linear ................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    7.4s remaining:    0.0s


[CV] ... model__C=1, model__kernel=linear, score=-0.605, total=   3.6s
[CV] model__C=1, model__kernel=linear ................................
[CV] ... model__C=1, model__kernel=linear, score=-0.644, total=   3.6s
[CV] model__C=1, model__kernel=linear ................................
[CV] ... model__C=1, model__kernel=linear, score=-0.687, total=   3.6s
[CV] model__C=10, model__kernel=linear ...............................
[CV] .. model__C=10, model__kernel=linear, score=-0.613, total=  13.8s
[CV] model__C=10, model__kernel=linear ...............................
[CV] .. model__C=10, model__kernel=linear, score=-0.632, total=  13.2s
[CV] model__C=10, model__kernel=linear ...............................
[CV] .. model__C=10, model__kernel=linear, score=-0.605, total=  14.5s
[CV] model__C=10, model__kernel=linear ...............................
[CV] .. model__C=10, model__kernel=linear, score=-0.645, total=  14.7s
[CV] model__C=10, model__kernel=linear ...............................
[CV] .

[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed: 109.2min finished


GridSearchCV(cv=5, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('scaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('model',
                                        SVR(C=1.0, cache_size=200, coef0=0.0,
                                            degree=3, epsilon=0.1,
                                            gamma='scale', kernel='rbf',
                                            max_iter=-1, shrinking=True,
                                            tol=0.001, verbose=False))],
                                verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'model__C': [1, 10, 100, 1000],
                          'model__kernel': ['linear']},
                         {'model__C': [10

In [ ]:
#El mejor modelo fue rbf, asi que optmizo esos parametros.
modelo= Pipeline([('scaler', StandardScaler()),
                    
                  ('model',SVR())
])

grilla = GridSearchCV(modelo,
                      {'model__gamma':[0.01,0.1,0.5], 'model__C':[500,1000,2000],'model__kernel':['rbf']},
                      cv = 5, scoring="neg_mean_squared_error",verbose=3
                      )
grilla.fit(x_train,y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] model__C=500, model__gamma=0.01, model__kernel=rbf ..............


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  model__C=500, model__gamma=0.01, model__kernel=rbf, score=-0.552, total=   6.4s
[CV] model__C=500, model__gamma=0.01, model__kernel=rbf ..............


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.4s remaining:    0.0s


[CV]  model__C=500, model__gamma=0.01, model__kernel=rbf, score=-0.555, total=   6.7s
[CV] model__C=500, model__gamma=0.01, model__kernel=rbf ..............


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   13.0s remaining:    0.0s


[CV]  model__C=500, model__gamma=0.01, model__kernel=rbf, score=-0.539, total=   6.3s
[CV] model__C=500, model__gamma=0.01, model__kernel=rbf ..............
[CV]  model__C=500, model__gamma=0.01, model__kernel=rbf, score=-0.588, total=   6.1s
[CV] model__C=500, model__gamma=0.01, model__kernel=rbf ..............
[CV]  model__C=500, model__gamma=0.01, model__kernel=rbf, score=-0.597, total=   6.5s
[CV] model__C=500, model__gamma=0.1, model__kernel=rbf ...............
[CV]  model__C=500, model__gamma=0.1, model__kernel=rbf, score=-0.465, total=  23.0s
[CV] model__C=500, model__gamma=0.1, model__kernel=rbf ...............
[CV]  model__C=500, model__gamma=0.1, model__kernel=rbf, score=-0.455, total=  23.0s
[CV] model__C=500, model__gamma=0.1, model__kernel=rbf ...............
[CV]  model__C=500, model__gamma=0.1, model__kernel=rbf, score=-0.500, total=  22.4s
[CV] model__C=500, model__gamma=0.1, model__kernel=rbf ...............
[CV]  model__C=500, model__gamma=0.1, model__kernel=rbf, scor

[Parallel(n_jobs=1)]: Done  45 out of  45 | elapsed: 78.9min finished


GridSearchCV(cv=5, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('scaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('model',
                                        SVR(C=1.0, cache_size=200, coef0=0.0,
                                            degree=3, epsilon=0.1,
                                            gamma='scale', kernel='rbf',
                                            max_iter=-1, shrinking=True,
                                            tol=0.001, verbose=False))],
                                verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'model__C': [500, 1000, 2000],
                         'model__gamma': [0.01, 0.1, 0.5],
                         'model__kernel'

In [ ]:
grilla.best_params_

{'model__C': 500, 'model__gamma': 0.5, 'model__kernel': 'rbf'}

In [ ]:
grilla.best_score_

-0.4166882337034369

In [ ]:
# Fit best model
modelo=grilla.best_estimator_
modelo.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('model',
                 SVR(C=500, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
                     gamma=0.5, kernel='rbf', max_iter=-1, shrinking=True,
                     tol=0.001, verbose=False))],
         verbose=False)

In [ ]:
y_pred_test = modelo.predict(x_test)
y_pred_test

array([24.97303484, 27.26514882, 14.37335791, ..., 33.72827841,
       26.46286771, 28.8285393 ])

In [ ]:
#se puede usar scoring='neg_root_mean_squared_error' tambien que seria la raiz
MSE_modelo=cross_val_score(modelo,x_test,y_test,cv=5,scoring='neg_mean_squared_error')
errores = -MSE_modelo
MSE_modelo


array([-0.5137263 , -0.75990751, -0.69712928, -0.64917979, -0.63670922])

In [ ]:
print(errores.mean(), errores.std())

0.6513304218113287 0.08128938354906176


In [ ]:
#Hay mucha diferencia entre el MSE de train y test, posiblemente esta sobreajustando.
modelo= Pipeline([('scaler', StandardScaler()),
                    
                  ('model',SVR())
])

grilla = GridSearchCV(modelo,
                      {'model__gamma':[0.1,0.5,0.7], 'model__C':[500,1000],'model__kernel':['rbf']},
                      cv = 5, scoring="neg_mean_squared_error",verbose=3
                      )
grilla.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] model__C=500, model__gamma=0.1, model__kernel=rbf ...............


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  model__C=500, model__gamma=0.1, model__kernel=rbf, score=-0.465, total=  23.1s
[CV] model__C=500, model__gamma=0.1, model__kernel=rbf ...............


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   23.1s remaining:    0.0s


[CV]  model__C=500, model__gamma=0.1, model__kernel=rbf, score=-0.455, total=  22.9s
[CV] model__C=500, model__gamma=0.1, model__kernel=rbf ...............


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   46.1s remaining:    0.0s


[CV]  model__C=500, model__gamma=0.1, model__kernel=rbf, score=-0.500, total=  22.3s
[CV] model__C=500, model__gamma=0.1, model__kernel=rbf ...............
[CV]  model__C=500, model__gamma=0.1, model__kernel=rbf, score=-0.485, total=  22.2s
[CV] model__C=500, model__gamma=0.1, model__kernel=rbf ...............
[CV]  model__C=500, model__gamma=0.1, model__kernel=rbf, score=-0.493, total=  22.3s
[CV] model__C=500, model__gamma=0.5, model__kernel=rbf ...............
[CV]  model__C=500, model__gamma=0.5, model__kernel=rbf, score=-0.401, total= 1.6min
[CV] model__C=500, model__gamma=0.5, model__kernel=rbf ...............
[CV]  model__C=500, model__gamma=0.5, model__kernel=rbf, score=-0.476, total= 1.5min
[CV] model__C=500, model__gamma=0.5, model__kernel=rbf ...............
[CV]  model__C=500, model__gamma=0.5, model__kernel=rbf, score=-0.357, total= 1.7min
[CV] model__C=500, model__gamma=0.5, model__kernel=rbf ...............
[CV]  model__C=500, model__gamma=0.5, model__kernel=rbf, score=-

[Parallel(n_jobs=1)]: Done  30 out of  30 | elapsed: 70.5min finished


GridSearchCV(cv=5, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('scaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('model',
                                        SVR(C=1.0, cache_size=200, coef0=0.0,
                                            degree=3, epsilon=0.1,
                                            gamma='scale', kernel='rbf',
                                            max_iter=-1, shrinking=True,
                                            tol=0.001, verbose=False))],
                                verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'model__C': [500, 1000],
                         'model__gamma': [0.1, 0.5, 0.7],
                         'model__kernel': ['rbf

In [ ]:
grilla.best_params_

{'model__C': 500, 'model__gamma': 0.7, 'model__kernel': 'rbf'}

In [ ]:
grilla.best_score_

-0.39498337539645434

In [ ]:
# Fit best model
modelo=grilla.best_estimator_
modelo.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('model',
                 SVR(C=500, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
                     gamma=0.7, kernel='rbf', max_iter=-1, shrinking=True,
                     tol=0.001, verbose=False))],
         verbose=False)

In [5]:

modelo= Pipeline([('scaler', StandardScaler()),
                    
                  ('model',SVR())
])

grilla = GridSearchCV(modelo,
                      [{'model__gamma':[0.7], 'model__C':[500],'model__kernel':['rbf']}],
                      cv = 5, scoring="neg_mean_squared_error",verbose=3
                      )
grilla.fit(x_train,y_train)

Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV] model__C=500, model__gamma=0.7, model__kernel=rbf ...............


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  model__C=500, model__gamma=0.7, model__kernel=rbf, score=-0.382, total= 2.4min
[CV] model__C=500, model__gamma=0.7, model__kernel=rbf ...............


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  2.4min remaining:    0.0s


[CV]  model__C=500, model__gamma=0.7, model__kernel=rbf, score=-0.442, total= 2.5min
[CV] model__C=500, model__gamma=0.7, model__kernel=rbf ...............


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  4.9min remaining:    0.0s


[CV]  model__C=500, model__gamma=0.7, model__kernel=rbf, score=-0.351, total= 2.5min
[CV] model__C=500, model__gamma=0.7, model__kernel=rbf ...............
[CV]  model__C=500, model__gamma=0.7, model__kernel=rbf, score=-0.395, total= 2.4min
[CV] model__C=500, model__gamma=0.7, model__kernel=rbf ...............
[CV]  model__C=500, model__gamma=0.7, model__kernel=rbf, score=-0.404, total= 2.4min


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed: 12.2min finished


GridSearchCV(cv=5, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('scaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('model',
                                        SVR(C=1.0, cache_size=200, coef0=0.0,
                                            degree=3, epsilon=0.1,
                                            gamma='scale', kernel='rbf',
                                            max_iter=-1, shrinking=True,
                                            tol=0.001, verbose=False))],
                                verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'model__C': [500], 'model__gamma': [0.7],
                          'model__kernel': ['rbf']}],
             pre_dispatch='2*n_jo

In [9]:
# Fit best model
modelo=grilla.best_estimator_
modelo.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('model',
                 SVR(C=500, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
                     gamma=0.7, kernel='rbf', max_iter=-1, shrinking=True,
                     tol=0.001, verbose=False))],
         verbose=False)

In [10]:

y_pred_test = modelo.predict(x_test)
y_pred_test

array([24.95973333, 27.21897993, 14.4931265 , ..., 33.83418448,
       26.11898519, 28.78667456])

In [12]:
print('Precisión del modelo usando el (MSE):')
score_testeo = mse(y_test,y_pred_test)

print (score_testeo)

Precisión del modelo usando el (MSE):
0.3416977894548662


In [13]:
#se importa el set de datos final
url = 'https://raw.githubusercontent.com/Jorge-89/Regresiones_TP_UNSAM/main/base_datos_estaciones_met_V3_test.csv'
df = pd.read_csv(url, sep=",")
df.columns


Index(['Unnamed: 0', 'fecha_completa', 'Fecha', 'Hora',
       'Temp_Alicia AgriculturaCba', 'Humedad_Alicia AgriculturaCba',
       'PP_Alicia AgriculturaCba', 'Temp_Las Varas AgriculturaCba',
       'Humedad_Las Varas AgriculturaCba', 'PP_Las Varas AgriculturaCba',
       'Temp_San Miguel - Establecimiento Don Luis',
       'Humedad_San Miguel - Establecimiento Don Luis',
       'PP_San Miguel - Establecimiento Don Luis',
       'Temp_San Miguel - Listello', 'Humedad_San Miguel - Listello',
       'PP_San Miguel - Listello', 'Temp_ San Miguel - Las Varillas',
       'Humedad_ San Miguel - Las Varillas', 'PP_ San Miguel - Las Varillas'],
      dtype='object')

In [14]:

x= df[[ 'Temp_Las Varas AgriculturaCba', 'Humedad_Las Varas AgriculturaCba',
        'Temp_San Miguel - Establecimiento Don Luis', 'Humedad_San Miguel - Establecimiento Don Luis',
       'Temp_San Miguel - Listello', 'Humedad_San Miguel - Listello',
       'Temp_ San Miguel - Las Varillas', 'Humedad_ San Miguel - Las Varillas']]
y= df["Temp_Alicia AgriculturaCba"]

In [15]:

y_pred = modelo.predict(x)
y_pred

array([19.7460993 , 19.73766783, 19.59174737, ..., 13.89781155,
       13.93528798, 14.0726416 ])

In [18]:

print('Precisión del modelo usando el MSE):')
score_testeo = mse(y_pred,y,squared=True)

print (score_testeo)


Precisión del modelo usando el MSE):
0.21384359445164441
